name: my_router_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.4.4 # 博客语法糖
  dio: ^3.0.10 # http
  async: ^2.4.1 #要使用Future的话需要引入dart.async
  flutter_easyloading: ^1.1.3
  connectivity: ^0.4.9+2 #监听手机网络
  flutter_easyrefresh: ^2.1.5 #Flutter上拉加载下拉刷新---flutter_easyrefresh
  shared_preferences: ^0.5.10 #可以利用本地存储SharedPreferences这个轻量级的存储类来保存键值对信息
  provider: ^4.3.2+1 #Flutter状态管理Provider
  fluttertoast: ^7.0.4 # 弹框 https://pub.dev/packages/fluttertoast#-installing-tab-
  widget_with_codeview: ^1.0.3 #codeview
  backdrop: ^0.4.4  #背景模糊
  stacked: ^1.7.6 #MVVM
  flutter_svg: ^0.19.1 #svg
  flutter_staggered_grid_view: ^0.3.3
  image_picker: ^0.6.7+22
  local_auth: any
  transparent_image: any
#  fluttertoast: any #弹窗，


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    -  assets/images/
    -  assets/images/photos/
    -  assets/json/creads.json
    -  lib/dart/class/super.dart
    -  lib/flutter_widget/app_bar/app_bar_ex.dart
    -  lib/flutter_widget/lists/tile_example.dart
    -  lib/flutter_widget/lists/listview_example.dart
    -  lib/flutter_pub/markdown/markdown_example.dart
    -  lib/flutter_pub/provider/example/provider_example.dart
    -  lib/flutter_pub/shard_preferences/example/shard_preferences.dart
    -  lib/http/dio/example/http_example.dart
    -  lib/http/http_modules/http_page_test_page.dart
    -  lib/navigator/based_on_using/navigator_based.dart
    -  lib/navigator/navigator_expert/nav_expert.dart
    -  lib/share_communication/communication/communication.dart
    -  lib/share_communication/shared_data_widget/shared_data_widget.dart
    -  lib/flutter_pub/stacked_pub/stacked_nonReactive.dart
    -  lib/layouts_or_widget/container/container.dart
    -  lib/based_component/button_style/button_style.dart

#    - assets/images/
#    - res/lottie/
#    - packages/flutter_gallery_assets/animated_images/animated_flutter_stickers.webp
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
